//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaDeRopa.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos_ventas
    {
        public int id { get; set; }
        public int idVenta { get; set; }
        public int idProducto { get; set; }
        public Nullable<int> precioUnitario { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> porcentaje_descuento { get; set; }
        public Nullable<decimal> importe { get; set; }
    
        public virtual productos productos { get; set; }
        public virtual ventas ventas { get; set; }
    }
}
